# -*- coding: utf-8 -*-
"""
test.py

This script tests my solver for Sortable's coding challenge using test data
generated by generate_test_data.py

"""

import io
import json

import solver

if __name__ == '__main__':

    products_by_man = solver.load_products('products.txt')

    with io.open('test_data.txt', 'r', encoding='utf-8') as test_file:
        score = 0
        count = 0

        for line in test_file:
            count += 1

            data = json.loads(line)

            listing = data['listing']
            product_name = data['product_name']

            result = solver.match_listing(listing, products_by_man)
            if result == product_name:
                score+=1
            else:
                print('-'*36 + " Failed " + '-'*36)
                print('Listing:\n' + listing['title'])
                print('Manufacturer: '+listing['manufacturer'])
                print(result + ' -> ' + product_name)

        print("Score: %d/%d = %f"%(score,count, (100. * score)/count))
